ci: Add PR review bot
melpa/melpa pull request #8904
Opened 2024-01-29 03:30 UTC by jcs090218

For https://github.com/melpa/melpa/issues/6714.

A few results:

- https://github.com/jcs-PR/melpa/pull/23 (Test #8900)
- https://github.com/jcs-PR/melpa/pull/24 (Test #8892)

The workflow file in steps:

1. Check to see if the PR is good to review (job `check`)
2. Install `Emacs` and `melpazoid` to test the package based on the PR number
3. Comment the result back to PR

2024-01-29 07:24 UTC, port19x reviewed
Couldn't we just omit the `check` section?
Why add a comment instead of just CI status via exit 0/1?
- [x] ~~Perhaps this can be extended to use emacs 28 and 30 too and do so [in parallel](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs).~~

2024-01-29 07:47 UTC, port19x requested changes

2024-01-29 07:47 UTC, port19x commented on .github/workflows/review-pr.yml
> +      - 'recipes/**'
rationale: [ignore draft PRs](https://github.com/orgs/community/discussions/25722#discussioncomment-3248917)
```suggestion
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - 'recipes/**'
```

2024-01-29 07:47 UTC, port19x commented on .github/workflows/review-pr.yml
> +  review:
rationale: [parallel multi-version build](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs)
```suggestion
  review:
    strategy:
      matrix:
        version: [28.2, 29.2, 30]
```

2024-01-29 07:47 UTC, port19x commented on .github/workflows/review-pr.yml
> +        version: 29.2
rationale: [parallel multi-version build](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs)
```suggestion
        version: ${{ matrix.version }}
```

2024-01-29 07:47 UTC, port19x commented on .github/workflows/review-pr.yml
> +    if: ${{ needs.check.outputs.status == 'success' }}
rationale: [ignore draft PRs](https://github.com/orgs/community/discussions/25722#discussioncomment-3248917)
```suggestion
    if: ${{ needs.check.outputs.status == 'success' }}
    if: github.event.pull_request.draft == false
```

2024-01-29 08:13 UTC, jcs090218 commented
> Couldn't we just omit the check section?

I don't prefer doing that since it will result a red mark ❌. Another approach is to use `continue-on-error`, but that's too messy compare to my approach.

> Why add a comment instead of just CI status via exit 0/1?

Those checks are opinionated, so it's better to post the comment out. Furthermore, I reckon people are unlikely to review the GitHub Actions log page to identify the error. 🤔

2024-01-29 09:16 UTC, port19x commented
> I don't prefer doing that since it will result a red mark ❌

That's kind of the point of CI, isn't it?
If melpazoid can't run due to a missing repo link, despite the PR template, that should be marked red.
Ideally we can rename check to sth like `check-repo-link`, that way it is even more apparent to the PR author where the red x comes from.
If melpazoid can run, perhaps it pulls the source from the recipe itself, then `check` is unnecessary.

> I reckon people are unlikely to review the GitHub Actions log page

Fair point, also since the melpa check does basically a 4 in 1, you can't see by what exactly failed where to work.
If there were separate github actions for byte-compiling, package-lint, checkdoc, etc. this would be less of an issue.

2024-01-29 09:24 UTC, jcs090218 commented
> That's kind of the point of CI, isn't it?
> If melpazoid can't run due to a missing repo link, despite the PR template, that should be marked red.
> If melpazoid can't run due to a missing repo link, despite the PR template, that should be marked red.
> If melpazoid can run, perhaps it pulls the source from the recipe itself, then check is unnecessary.

PR doesn't always refer to a new package. Like this PR is not relevant to "Adding a new recipe", making it red will only cause confusions.

> Fair point, also since the melpa check does basically a 4 in 1, you can't see by what exactly failed where to work.
> If there were separate github actions for byte-compiling, package-lint, checkdoc, etc. this would be less of an issue.

FYI, [Eask](https://github.com/emacs-eask/cli) does that, but not the same standard as MELPA.

2024-01-29 09:25 UTC, port19x commented
You're already catching non-package PRs via
```
    paths:
      - 'recipes/**'
```

2024-01-29 09:34 UTC, port19x commented
Would it be sufficient to catch if anything else has been modified?
Also why would you do that? 
Wouldn't only melpa maintainers and contributors ever touch sth outside of recipes?

2024-01-29 09:37 UTC, jcs090218 commented
> Would it be sufficient to catch if anything else has been modified?

For example?

> Wouldn't only melpa maintainers and contributors ever touch sth outside of recipes?

Yes, but we don't assume people won't, right?

2024-01-29 09:40 UTC, port19x commented
It is possible to have a complimentary check that asserts the inverse of the recipes path, but I'm not sure how elegant that is.

> Yes, but we don't assume people won't, right?

I would be in favor of a separation of concerns.
Can recipe authors decide to contribute to melpa beyond their recipe? definitely.
Should both the recipe contribution and the general contribution share the same PR? I believe not

2024-01-29 09:54 UTC, jcs090218 commented
> It is possible to have a complimentary check that asserts the inverse of the recipes path, but I'm not sure how elegant that is.

Let me know if you figure it out! :)

> I would be in favor of a separation of concerns.
> Can recipe authors decide to contribute to melpa beyond their recipe? definitely.
> Should both the recipe contribution and the general contribution share the same PR? I believe not

Sorry, I don't think it's worth discussing this since it only requires me to delete a few lines. You have your point, and I see it; I used to have the same perspective as you. I'll agree to disagree since it's not worth the effort!

2024-02-18 17:29 UTC, riscy commented
Hi @jcs090218 - I apologize for having not looked at this yet, most of my MELPA bandwidth is going into reviewing recipes at the moment.

I'll give this the closer look it deserves, but I will note that I've also been hesitant about melpazoid's reliability for reviewing recipes in the general case.  For a lot of simple recipes it works.  For a lot of nontrivial recipes I'm making a fix here or there, or discovering that some of the output is incorrect and needs to be hand-edited before being passed to the author as "advice".

2024-02-18 20:17 UTC, jcs090218 commented
> I'll give this the closer look it deserves, but I will note that I've also been hesitant about melpazoid's reliability for reviewing recipes in the general case.

Yeah, I agree. There are a few things need to improve to make it perfect.

> For a lot of simple recipes it works. For a lot of nontrivial recipes I'm making a fix here or there, or discovering that some of the output is incorrect and needs to be hand-edited before being passed to the author as "advice".

I'm not too worried about this since many big repo are doing things like this. (1) They simply put a note in the comment, for example "This is an automated test, please ignore it if it doesn't look right. There will soon be a maintainer to review it!", etc. Of course, you can put any note you want. (2) Even if something went wrong, you can always change `review-pr.yml` (this PR) or `melpazoid` to improve the result since you are the maintainer of MELPA and author of `melpazoid`.

2024-09-26 10:43 UTC, port19x commented
What is the current status on melpa CI?

2024-09-29 17:00 UTC, riscy commented
> What is the current status on melpa CI?

CI is currently not checking the things that it should (I'll need to look at fixing that, because I think I implemented a lot of what's there currently with GitHub Actions).

In my past experience, CI usually takes a few continuous hours of work/verification to make sure everything is running correctly.  I've been bumping this down on my priority list for quite a while, admittedly, because it's not mission critical (especially with the active code reviews we do).  I apologize for the big wait on that!

2024-09-30 06:10 UTC, port19x commented
You'll ultimately be the one to benefit the most from CI, so do it whenever you feel is the appropiate time. Thanks for the update

2025-02-05 23:54 UTC, closed without merging